In [142]:
import numpy as np
import pickle
import json

In [143]:

with open("food.json","r", encoding="utf-8") as f:
    food_data = json.load(f)

In [144]:
food_data

[{'meal_type': 'Breakfast',
  'dish_name': 'Овсянка с фруктами',
  'calories': 150,
  'protein': 5,
  'fat': 3,
  'carbohydrates': 27},
 {'meal_type': 'Breakfast',
  'dish_name': 'Яичница с овощами',
  'calories': 200,
  'protein': 14,
  'fat': 16,
  'carbohydrates': 2},
 {'meal_type': 'Breakfast',
  'dish_name': 'Тост с авокадо',
  'calories': 250,
  'protein': 6,
  'fat': 15,
  'carbohydrates': 30},
 {'meal_type': 'Breakfast',
  'dish_name': 'Панкейки с медом',
  'calories': 300,
  'protein': 7,
  'fat': 9,
  'carbohydrates': 50},
 {'meal_type': 'Breakfast',
  'dish_name': 'Каша рисовая с молоком',
  'calories': 200,
  'protein': 4,
  'fat': 6,
  'carbohydrates': 32},
 {'meal_type': 'Breakfast',
  'dish_name': 'Смузи с ягодами',
  'calories': 180,
  'protein': 2,
  'fat': 1,
  'carbohydrates': 38},
 {'meal_type': 'Breakfast',
  'dish_name': 'Чиабатта с сыром',
  'calories': 220,
  'protein': 10,
  'fat': 7,
  'carbohydrates': 30},
 {'meal_type': 'Breakfast',
  'dish_name': 'Кефир с о

In [145]:
breakfast = []
lunch = []
dinner = []

In [146]:
for i in range(len(food_data)):
    if food_data[i]['meal_type'] == 'Breakfast' :
        breakfast.append(food_data[i])
    elif food_data[i]['meal_type'] == 'Dinner' :
        dinner.append(food_data[i])
    elif food_data[i]['meal_type'] == 'Lunch' :
        lunch.append(food_data[i])

In [147]:
len(breakfast), len(lunch), len(dinner)

(21, 30, 24)

In [149]:
# mocked_breakfast_data = {'meal_type': 'Breakfast',
#  'dish_name': 'Овсянка с фруктами',
#  'calories': 150,
#  'protein': 5,
#  'fat': 3,
#  'carbohydrates': 27}

In [169]:
breakfast_list = []
ids_breakfast = []
for i in range(len(breakfast)):
    temp = list(breakfast[i].values())

    ids_breakfast.append(temp[1])
    breakfast_list.append(temp[2:])


In [152]:
breakfast_list = np.array(breakfast_list)
breakfast_list

array([[150,   5,   3,  27],
       [200,  14,  16,   2],
       [250,   6,  15,  30],
       [300,   7,   9,  50],
       [200,   4,   6,  32],
       [180,   2,   1,  38],
       [220,  10,   7,  30],
       [200,   8,  10,  20],
       [350,   4,  15,  50],
       [350,   8,  10,  60],
       [150,   2,   0,  36],
       [300,   8,  10,  50],
       [220,  10,   7,  36],
       [250,   9,   6,  43],
       [400,  15,  20,  30],
       [200,  12,   5,  25],
       [220,  12,  10,  25],
       [200,   6,   4,  36],
       [250,  12,  10,  20],
       [150,   4,   2,  28],
       [300,   8,  15,  40]])

In [153]:
mock_breakfast = breakfast_list[0]


In [154]:
def cosine_similarity(elem, arr):

    result = []
    for i in arr:

        dot_product = np.dot(i, elem)
        norm_a = np.linalg.norm(i)
        norm_b = np.linalg.norm(elem)
        result.append(dot_product / (norm_a * norm_b))

    return np.array(result)

In [155]:
mock_breakfast

array([150,   5,   3,  27])

In [156]:
# mock_breakfast = np.array([2200,34,23,2])

In [157]:
breakfast_list

array([[150,   5,   3,  27],
       [200,  14,  16,   2],
       [250,   6,  15,  30],
       [300,   7,   9,  50],
       [200,   4,   6,  32],
       [180,   2,   1,  38],
       [220,  10,   7,  30],
       [200,   8,  10,  20],
       [350,   4,  15,  50],
       [350,   8,  10,  60],
       [150,   2,   0,  36],
       [300,   8,  10,  50],
       [220,  10,   7,  36],
       [250,   9,   6,  43],
       [400,  15,  20,  30],
       [200,  12,   5,  25],
       [220,  12,  10,  25],
       [200,   6,   4,  36],
       [250,  12,  10,  20],
       [150,   4,   2,  28],
       [300,   8,  15,  40]])

In [158]:
results = cosine_similarity(mock_breakfast, breakfast_list)

In [159]:
results[results==1] = 0 
results

array([0.        , 0.98351224, 0.99745189, 0.99981947, 0.9996769 ,
       0.99920992, 0.99895196, 0.99646049, 0.99885739, 0.99987686,
       0.9979614 , 0.99980834, 0.99973331, 0.99995853, 0.99422653,
       0.99819207, 0.99734869, 0.99999463, 0.99487359, 0.99993596,
       0.99850034])

In [190]:
len(ids_breakfast), len(results)

(21, 21)

In [197]:
results

array([0.        , 0.98351224, 0.99745189, 0.99981947, 0.9996769 ,
       0.99920992, 0.99895196, 0.99646049, 0.99885739, 0.99987686,
       0.9979614 , 0.99980834, 0.99973331, 0.99995853, 0.99422653,
       0.99819207, 0.99734869, 0.99999463, 0.99487359, 0.99993596,
       0.99850034])

In [200]:
id_max = np.argmax(results)

In [202]:
breakfast_list[id_max], ids_breakfast[id_max]

([200, 6, 4, 36], 'Пшенная каша с тыквой')